#!/bin/bash
echo "File processor initiliazed."

echo "Extracting zipped files..."
unzip -B '*.zip'
rm *.zip
echo "Complete."

echo "Removing duplicates (pass 1)..."
rmlint
./rmlint.sh -d
rm rmlint.json
echo "Complete."

echo "Renaming all files..."
ren
echo "Complete."

echo "Removing metadata, pass 1..."
exiftool -all= -overwrite_original -r .
echo "Complete."

echo "Removing all files less than 100k..."
find . -maxdepth 1 -type f -size -100k -delete
echo "Complete."

find . -type f -name "*.webp" -print0 | while IFS= read -r -d '' file; do
    file_type=$(identify -format "%m" "$file")
    case "$file_type" in
        WEBP)
            echo "Converting $file to PNG"
            magick "$file" "${file%.webp}.png"
            rm "$file"
            ;;
        GIF)
            echo "Converting $file to GIF"
            magick "$file" "${file%.webp}.gif"
            rm "$file"
            ;;
        *)
            echo "$file is not a WEBP file or is in an unexpected format, skipping."
            ;;
    esac
done

echo "Converting JPGs less than 1MiB to PNG..."
find . -type f \( -name "*.jpg" \) -size -2M -print0 | while IFS= read -r -d '' file; do
    if mogrify -format png "$file"; then
        rm "$file"
    else
        echo "Failed to convert $file"
    fi
done
echo "Complete."

echo "Removing metadata, pass 2..."
exiftool -all= -overwrite_original -r .
echo "Complete."

echo "Removing duplicates, pass 2..."
rmlint
./rmlint.sh -d
rm rmlint.json
echo "Complete."

echo "Removing all files less than 1MiB..." 
find . -maxdepth 1 -type f -size -2M -delete
echo "Complete."
 
echo "File processing complete."
